tasks:
  - init: git remote set-url origin git@github.com:ashrith-a/ashrith-a-MethodParameters.git && sed "s/\r$//" commit-command.sh | bash && gp open README.md
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - revaturePro.revature-labs